// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO1_j-DmTQcjaMlg_mKNgbWSbOOKRGgtM',
    appId: '1:343606672728:android:d4325521b1c4e3b83ab92d',
    messagingSenderId: '343606672728',
    projectId: 'industryhub-981ff',
    storageBucket: 'industryhub-981ff.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyPTrpRNyQJZZKB_enrJXY-wOZ8V0TOuk',
    appId: '1:343606672728:ios:a2fb5c42de53bd153ab92d',
    messagingSenderId: '343606672728',
    projectId: 'industryhub-981ff',
    storageBucket: 'industryhub-981ff.firebasestorage.app',
    iosBundleId: 'com.example.industryhub',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyPTrpRNyQJZZKB_enrJXY-wOZ8V0TOuk',
    appId: '1:343606672728:ios:a2fb5c42de53bd153ab92d',
    messagingSenderId: '343606672728',
    projectId: 'industryhub-981ff',
    storageBucket: 'industryhub-981ff.firebasestorage.app',
    iosBundleId: 'com.example.industryhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7o-SRivtcL0tfrJbfCHNbe8aLHHDqdlk',
    appId: '1:343606672728:web:21cdb5e182e28ce43ab92d',
    messagingSenderId: '343606672728',
    projectId: 'industryhub-981ff',
    authDomain: 'industryhub-981ff.firebaseapp.com',
    storageBucket: 'industryhub-981ff.firebasestorage.app',
    measurementId: 'G-32B8R13K8C',
  );
}
